import Navbar from "@/components/common/navbar";
import "./globals.css";
import Footer from "@/components/common/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#505050] h-full flex flex-col">
        <div className="">
          <Navbar />
        </div>
        <div className="px-10 py-24">{children}</div>
        <div className="">
          <Footer />
        </div>
      </body>
    </html>
  );
}
